#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 24 17:33:38 YEKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=14
shaderPack=photon_v1.2a.zip
