#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 27 18:49:58 YEKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=photon_v1.2a.zip
